# Generated by Django 6.0.4 on 2026-05-01 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('REGISTER', 'Registration'), ('ACCOUNT_LOCKED', 'Account Locked'), ('BRUTE_FORCE', 'Brute Force Attempt'), ('XSS_ATTEMPT', 'XSS Attempt'), ('SQLI_ATTEMPT', 'SQLi Attempt'), ('ACCESS_DENIED', 'Access Denied'), ('FILE_UPLOAD_BLOCKED', 'File Upload Blocked'), ('SSRF_ATTEMPT', 'SSRF Attempt'), ('CSRF_ATTEMPT', 'CSRF Attempt'), ('SUSPICIOUS', 'Suspicious Activity')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_threat', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
